#!/bin/sh
export XDG_CURRENT_DESKTOP=dwl
export XDG_SESSION_DESKTOP=dwl
export XDG_SESSION_TYPE=wayland

conf="${XDG_CONFIG_HOME:-$HOME/.config}/dwl"
state="${XDG_STATE_HOME:-$HOME/.local/state}"
mkdir -p "$state"

[ -r "$conf/env" ] && . "$conf/env"

dwl -s "
  exec <&-
  dbus-update-activation-environment --systemd \
    WAYLAND_DISPLAY DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_DESKTOP XDG_SESSION_TYPE
  [ -x '$conf/autostart' ] && exec '$conf/autostart'
" >"$state/dwl.log" 2>&1

systemctl --user stop \
  xdg-desktop-portal.service \
  xdg-desktop-portal-wlr.service \
  xdg-desktop-portal-gtk.service 2>/dev/null
