general {
  after_sleep_cmd=swaymsg "output * power on"
  before_sleep_cmd=loginctl lock-session
  ignore_dbus_inhibit=false
  lock_cmd=mshell lock lock
}

listener {
  on-timeout=mshell lock lock
  timeout=300
}

listener {
  on-resume=swaymsg "output * power on"
  on-timeout=swaymsg "output * power off"
  timeout=360
}

listener {
  on-timeout=systemctl suspend
  timeout=480
}
